// src/components/Background.tsx
import {createSignal, onCleanup, onMount, Show} from "solid-js";
import { state, setState } from "~/store";
import { toast } from "~/components/ui/Toast";

const WALL_COUNT = 10;

/** 拼接本地壁纸地址 */
const wallUrl = (n: number) =>
  import.meta.env.BASE_URL + "images/wallpapers/wall-" + String(n).padStart(2, "0") + ".jpg";

const randomWall = () => wallUrl(Math.floor(Math.random() * WALL_COUNT) + 1);

/** 每日一图（按天轮换） */
const dailyWall = () => {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return wallUrl((dayOfYear % WALL_COUNT) + 1);
};

interface BackgroundProps {
  onLoadComplete?: () => void;
}

/** 壁纸：默认 / 每日一图 / 随机；加载完成回调 */
export function Background(props: BackgroundProps) {
  const [bgUrl, setBgUrl] = createSignal(wallUrl(1));
  const [showImg, setShowImg] = createSignal(false);
  let timer: number | null = null;
  let emitted = false;
  // 保存 img 元素引用，用于 hydration 后补触发 onLoad
  let imgEl: HTMLImageElement | undefined;

  const changeBg = () => {
    // 当前仅统一使用本地壁纸：默认/随机风景/随机动漫 → 随机；每日一图 → 按天
    setBgUrl(state.coverType === "1" ? dailyWall() : randomWall());
  };

  const imgLoadComplete = () => {
    timer = window.setTimeout(() => {
      setState({ imgLoadStatus: true });
      setShowImg(true);
    }, Math.floor(Math.random() * 300) + 300);
    // 预取另一张壁纸(随机)，便于"展示壁纸"切换时更跟手
    const next = new Image();
    next.src = state.coverType === "1" ? dailyWall() : randomWall();
  };

  const imgLoadError = () => {
    console.error("壁纸加载失败");
    toast("壁纸加载失败，已临时切换", { type: "error" });
    setBgUrl(randomWall());
  };

  onMount(() => {
    changeBg();
    // SSR 场景：壁纸可能在 hydration 绑定 onLoad 前就已加载完成（本地/缓存），
    // load 事件被错过会导致 imgLoadStatus 一直为 false、正文永不显示。
    // 挂载后检查图片是否已加载完成，若是则手动补触发。
    requestAnimationFrame(() => {
      if (imgEl && imgEl.complete && imgEl.naturalWidth > 0 && !state.imgLoadStatus) {
        imgLoadComplete();
      }
    });
  });

  onCleanup(() => {
    if (timer) clearTimeout(timer);
  });

  // 封面显隐后触发加载完成（一次性）
  const onAnimationEnd = () => {
    if (!emitted && state.imgLoadStatus) {
      emitted = true;
      props.onLoadComplete?.();
    }
  };

  return (
    <div classList={{ cover: true, show: state.backgroundShow }}>
      <img
        ref={imgEl}
        src={bgUrl()}
        class="bg"
        alt="cover"
        fetchpriority="high"
        decoding="async"
        style={{ display: showImg() ? "" : "none" }}
        onLoad={imgLoadComplete}
        onError={imgLoadError}
        onAnimationEnd={onAnimationEnd}
      />
      <div classList={{ gray: true, hidden: state.backgroundShow }} />
      <Show when={state.backgroundShow && state.coverType !== "3"}>
        <a class="down" href={bgUrl()} target="_blank">
          下载壁纸
        </a>
      </Show>
    </div>
  );
}

// src/components/Background.vue
<template>
  <div :class="store.backgroundShow ? 'cover show' : 'cover'">
    <img
      v-show="store.imgLoadStatus"
      :src="bgUrl"
      class="bg"
      alt="cover"
      @load="imgLoadComplete"
      @error.once="imgLoadError"
      @animationend="imgAnimationEnd"
    />
    <div :class="store.backgroundShow ? 'gray hidden' : 'gray'" />
    <Transition name="fade" mode="out-in">
      <a
        v-if="store.backgroundShow && store.coverType != '3'"
        class="down"
        :href="bgUrl"
        target="_blank"
      >
        下载壁纸
      </a>
    </Transition>
  </div>
</template>

<script setup>
import { mainStore } from "@/store";
import { Error } from "@icon-park/vue-next";

const store = mainStore();
const bgUrl = ref(null);
const imgTimeout = ref(null);
const emit = defineEmits(["loadComplete"]);

// 本地壁纸数量（public/images/wallpapers/wall-01.jpg ~ wall-10.jpg）
const WALL_COUNT = 10;

// 拼接本地壁纸地址（兼容 GitHub Pages 子路径）
const wallUrl = (n) =>
  import.meta.env.BASE_URL + "images/wallpapers/wall-" + String(n).padStart(2, "0") + ".jpg";

// 随机壁纸
const randomWall = () => wallUrl(Math.floor(Math.random() * WALL_COUNT) + 1);

// 每日一图（按天轮换）
const dailyWall = () => {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now - start) / 86400000);
  return wallUrl((dayOfYear % WALL_COUNT) + 1);
};

// 更换壁纸链接
const changeBg = (type) => {
  if (type == 1) {
    // 每日一图：每天固定一张
    bgUrl.value = dailyWall();
  } else {
    // 默认壁纸 / 随机风景 / 随机动漫：均从本地壁纸随机
    bgUrl.value = randomWall();
  }
};

// 图片加载完成
const imgLoadComplete = () => {
  imgTimeout.value = setTimeout(
    () => {
      store.setImgLoadStatus(true);
    },
    Math.floor(Math.random() * (600 - 300 + 1)) + 300,
  );
};

// 图片动画完成
const imgAnimationEnd = () => {
  console.log("壁纸加载且动画完成");
  // 加载完成事件
  emit("loadComplete");
};

// 图片显示失败
const imgLoadError = () => {
  console.error("壁纸加载失败：", bgUrl.value);
  ElMessage({
    message: "壁纸加载失败，已临时切换回默认",
    icon: h(Error, {
      theme: "filled",
      fill: "#efefef",
    }),
  });
  // 本地壁纸加载失败时换一张本地壁纸重试
  bgUrl.value = randomWall();
};

// 监听壁纸切换
watch(
  () => store.coverType,
  (value) => {
    changeBg(value);
  },
);

onMounted(() => {
  // 加载壁纸
  changeBg(store.coverType);
});

onBeforeUnmount(() => {
  clearTimeout(imgTimeout.value);
});
</script>

<style lang="scss" scoped>
.cover {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  transition: 0.25s;
  z-index: -1;

  &.show {
    z-index: 1;
  }

  .bg {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    backface-visibility: hidden;
    filter: blur(20px) brightness(0.3);
    transition:
      filter 0.3s,
      transform 0.3s;
    animation: fade-blur-in 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
    animation-delay: 0.45s;
  }
  .gray {
    opacity: 1;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-image: radial-gradient(rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.5) 100%),
      radial-gradient(rgba(0, 0, 0, 0) 33%, rgba(0, 0, 0, 0.3) 166%);

    transition: 1.5s;
    &.hidden {
      opacity: 0;
      transition: 1.5s;
    }
  }
  .down {
    font-size: 16px;
    color: white;
    position: absolute;
    bottom: 30px;
    left: 0;
    right: 0;
    margin: 0 auto;
    display: block;
    padding: 20px 26px;
    border-radius: 8px;
    background-color: #00000030;
    width: 120px;
    height: 30px;
    display: flex;
    justify-content: center;
    align-items: center;
    &:hover {
      transform: scale(1.05);
      background-color: #00000060;
    }
    &:active {
      transform: scale(1);
    }
  }
}
</style>
