// src/components/Footer.tsx
import { Show } from "solid-js";
import { state } from "~/store";
import { Icon } from "~/assets/icons";

const fullYear = new Date().getFullYear();
const siteStart = import.meta.env.VITE_SITE_START as string | undefined;
const startYear =
  siteStart && siteStart.length >= 4 ? siteStart.substring(0, 4) : null;
const siteIcp = import.meta.env.VITE_SITE_ICP as string | undefined;
const siteAuthor = import.meta.env.VITE_SITE_AUTHOR as string | undefined;

const siteUrl = () => {
  const url = import.meta.env.VITE_SITE_URL as string | undefined;
  if (!url || !url.includes(".")) return import.meta.env.BASE_URL;
  if (!url.startsWith("http://") && !url.startsWith("https://")) return "//" + url;
  return url;
};

/** 页脚：版权信息（或正在播放的歌词） */
export function Footer() {
  const showLrc = () => state.playerState && state.playerLrcShow;
  const showRange = () => startYear !== null && Number(startYear) < fullYear;

  return (
    <footer id="footer" classList={{ blur: state.footerBlur }}>
      {!showLrc() ? (
        <div class="power">
          <span>
            <span classList={{ "c-hidden": !showRange(), hidden: true }}>Copyright&nbsp;</span>
            &copy;
            <Show when={showRange()}>
              <span class="site-start">{startYear} - </span>
            </Show>
            {fullYear} <a href={siteUrl()}>{siteAuthor}</a>
          </span>
          <Show when={false}>
            <span class="hidden">&amp;&nbsp;Made&nbsp;by&nbsp;imsyy</span>
          </Show>
          <Show when={siteIcp}>
            <span>
              &amp; <a href="https://beian.miit.gov.cn" target="_blank">{siteIcp}</a>
            </span>
          </Show>
        </div>
      ) : (
        <div class="lrc">
          <div class="lrc-all">
            <Icon name="music" size={18} />
            <span class="lrc-text text-hidden">{state.playerLrc}</span>
            <Icon name="music" size={18} />
          </div>
        </div>
      )}
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer id="footer" :class="store.footerBlur ? 'blur' : null">
    <Transition name="fade" mode="out-in">
      <div v-if="!store.playerState || !store.playerLrcShow" class="power">
        <span>
          <span :class="startYear < fullYear ? 'c-hidden' : 'hidden'">Copyright&nbsp;</span>
          &copy;
          <span v-if="startYear < fullYear"
            class="site-start">
            {{ startYear }}
            -
          </span>
          {{ fullYear }}
          <a :href="siteUrl">{{ siteAuthor }}</a>
        </span>
        <!-- 以下信息请不要修改哦 -->
        <span class="hidden">
          &amp;&nbsp;Made&nbsp;by
          <a :href="config.github" target="_blank">
            {{ config.author }}
          </a>
        </span>
        <!-- 站点备案 -->
        <span>
          &amp;
          <a v-if="siteIcp" href="https://beian.miit.gov.cn" target="_blank">
            {{ siteIcp }}
          </a>
        </span>
      </div>
      <div v-else class="lrc">
        <Transition name="fade" mode="out-in">
          <div class="lrc-all" :key="store.getPlayerLrc">
            <music-one theme="filled" size="18" fill="#efefef" />
            <span class="lrc-text text-hidden" v-html="store.getPlayerLrc" />
            <music-one theme="filled" size="18" fill="#efefef" />
          </div>
        </Transition>
      </div>
    </Transition>
  </footer>
</template>

<script setup>
import { MusicOne } from "@icon-park/vue-next";
import { mainStore } from "@/store";
import config from "@/../package.json";

const store = mainStore();
const fullYear = new Date().getFullYear();

// 加载配置数据
// const siteStartDate = ref(import.meta.env.VITE_SITE_START);
const startYear = ref(
  import.meta.env.VITE_SITE_START?.length >= 4 ? 
  import.meta.env.VITE_SITE_START.substring(0, 4) : null
);
const siteIcp = ref(import.meta.env.VITE_SITE_ICP);
const siteAuthor = ref(import.meta.env.VITE_SITE_AUTHOR);
const siteUrl = computed(() => {
  const url = import.meta.env.VITE_SITE_URL;
  // 未配置域名时，作者链接指向站点首页本身
  if (!url || !url.includes(".")) return import.meta.env.BASE_URL;
  // 判断协议前缀
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    return "//" + url;
  }
  return url;
});
</script>

<style lang="scss" scoped>
#footer {
  width: 100%;
  position: absolute;
  bottom: 0;
  left: 0;
  height: 46px;
  line-height: 46px;
  text-align: center;
  z-index: 0;
  font-size: 14px;
  // 文字不换行
  word-break: keep-all;
  white-space: nowrap;
  .power {
    animation: fade 0.3s;
  }
  .lrc {
    padding: 0 20px;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    .lrc-all {
      width: 98%;
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      .lrc-text {
        margin: 0 8px;
      }
      .i-icon {
        width: 18px;
        height: 18px;
        display: inherit;
      }
    }
  }
  &.blur {
    backdrop-filter: blur(10px);
    background: rgb(0 0 0 / 25%);
    font-size: 16px;
  }
  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 0.15s ease-in-out;
  }
  @media (max-width: 720px) {
    font-size: 0.9rem;
    &.blur {
      font-size: 0.9rem;
    }
  }
  @media (max-width: 560px) {
    .c-hidden {
      display: none;
    }
  }
  @media (max-width: 480px) {
    .hidden {
      display: none;
    }
  }
}
</style>
