// src/components/SocialLinks.tsx
import { For, createSignal } from "solid-js";
import socialLinks from "~/assets/socialLinks.json";

/** 解析图标路径：绝对 URL 或以 / 开头时拼 BASE_URL（兼容子路径部署） */
const resolveIcon = (icon: string): string => {
  if (!icon) return icon;
  if (/^https?:\/\//.test(icon)) return icon;
  if (icon.startsWith("/")) return import.meta.env.BASE_URL.replace(/\/+$/, "") + icon;
  return icon;
};

/** 社交链接行 */
export function SocialLinks() {
  const [tipText, setTipText] = createSignal("通过这里联系我吧");
  return (
    <div class="social">
      <div class="link">
        <For each={socialLinks}>
          {(item) => (
            <a
              href={item.url}
              target="_blank"
              rel="noreferrer"
              class="social-link"
              data-tip={item.tip}
              onMouseEnter={() => setTipText(item.tip)}
              onMouseLeave={() => setTipText("通过这里联系我吧")}
            >
              <img class="icon" src={resolveIcon(item.icon)} height="24" alt={item.name} />
            </a>
          )}
        </For>
      </div>
      <span class="tip">{tipText()}</span>
    </div>
  );
}

// src/components/SocialLinks.vue
<template>
  <!-- 社交链接 -->
  <div class="social">
    <div class="link">
      <a
        v-for="item in socialLinks"
        :key="item.name"
        :href="item.url"
        target="_blank"
        @mouseenter="socialTip = item.tip"
        @mouseleave="socialTip = '通过这里联系我吧'"
      >
        <img class="icon" :src="resolveIcon(item.icon)" height="24" />
      </a>
    </div>
    <span class="tip">{{ socialTip }}</span>
  </div>
</template>

<script setup>
import socialLinks from "@/assets/socialLinks.json";

// 图标路径以 / 开头时，拼接 BASE_URL（生产为 /home/）以兼容 GitHub Pages 子路径部署
const resolveIcon = (icon) => {
  if (!icon) return icon;
  if (/^https?:\/\//.test(icon)) return icon;
  if (icon.startsWith("/")) {
    return import.meta.env.BASE_URL.replace(/\/+$/, "") + icon;
  }
  return icon;
};

// 社交链接提示
const socialTip = ref("通过这里联系我吧");
</script>

<style lang="scss" scoped>
.social {
  margin-top: 1rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 460px;
  width: 100%;
  height: 42px;
  background-color: transparent;
  border-radius: 6px;
  backdrop-filter: blur(0);
  animation: fade 0.5s;
  transition:
    background-color 0.3s,
    backdrop-filter 0.3s;
  @media (max-width: 840px) {
    max-width: 100%;
    justify-content: center;
    .link {
      justify-content: space-evenly !important;
      width: 90%;
    }
    .tip {
      display: none !important;
    }
  }

  .link {
    display: flex;
    align-items: center;
    justify-content: center;
    a {
      display: inherit;
      .icon {
        margin: 0 12px;
        transition: transform 0.3s;
        &:hover {
          transform: scale(1.1);
        }
        &:active {
          transform: scale(1);
        }
      }
    }
  }
  .tip {
    display: none;
    margin-right: 12px;
    animation: fade 0.5s;
  }
  @media (min-width: 768px) {
    &:hover {
      background-color: #00000040;
      backdrop-filter: blur(5px);
      .tip {
        display: block;
      }
    }
  }
}
</style>
